List<dynamic> contact_data = [
  {
    'name': 'Angel Curtis',
    "message": 'Please help me find a good monitor for trading',
    "profileimage": 'assets/profile/profile1.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Zaire Dorwart',
    "message": 'Gacor pisan kang',
    "profileimage": 'assets/profile/profile2.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Kelas Malam',
    "message": 'Bima: no one come today ',
    "profileimage": 'assets/profile/profile4.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Jocelyn Gouse',
    "message": "You're now an admin",
    "profileimage": 'assets/profile/profile3.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Jaylon Dias',
    "message": 'Buy back 10k gallons, top up credit, bills for work',
    "profileimage": 'assets/profile/profile5.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Chance Rhiel Madson',
    "message": 'Thank You mate!',
    "profileimage": 'assets/profile/profile6.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Livia Dias',
    "message": 'You Want to leave now',
    "profileimage": 'assets/profile/profile7.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Angel Curtis',
    "message": 'Please help me find a good monitor for trading',
    "profileimage": 'assets/profile/profile1.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Zaire Dorwart',
    "message": 'Gacor pisan kang',
    "profileimage": 'assets/profile/profile2.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Kelas Malam',
    "message": 'Bima: no one come today ',
    "profileimage": 'assets/profile/profile4.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Jocelyn Gouse',
    "message": "You're now an admin",
    "profileimage": 'assets/profile/profile3.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Jaylon Dias',
    "message": 'Buy back 10k gallons, top up credit, bils for work',
    "profileimage": 'assets/profile/profile5.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Chance Rhiel Madson',
    "message": 'Thank You mate!',
    "profileimage": 'assets/profile/profile6.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Livia Dias',
    "message": 'You Want to leave now',
    "profileimage": 'assets/profile/profile7.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Angel Curtis',
    "message": 'Please help me find a good monitor for trading',
    "profileimage": 'assets/profile/profile1.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Zaire Dorwart',
    "message": 'Gacor pisan kang',
    "profileimage": 'assets/profile/profile2.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Kelas Malam',
    "message": 'Bima: no one come today ',
    "profileimage": 'assets/profile/profile4.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Jocelyn Gouse',
    "message": "You're now an admin",
    "profileimage": 'assets/profile/profile3.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Jaylon Dias',
    "message": 'Buy back 10k gallons, top up credit, bils for work',
    "profileimage": 'assets/profile/profile5.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
  {
    'name': 'Chance Rhiel Madson',
    "message": 'Thank You mate!',
    "profileimage": 'assets/profile/profile6.jpg',
    "messagetime": '02:11',
    "readUndread": '2',
  },
  {
    'name': 'Livia Dias',
    "message": 'You Want to leave now',
    "profileimage": 'assets/profile/profile7.jpg',
    "messagetime": '02:11',
    "readUndread": '',
  },
];

List<dynamic> status_data = [
  {'profile': 'assets/profile/profile8.jpg', 'name': 'Terry'},
  {'profile': 'assets/profile/profile9.jpg', 'name': 'Craig'},
  {'profile': 'assets/profile/profile6.jpg', 'name': 'Roger'},
  {'profile': 'assets/profile/profile4.jpg', 'name': 'noian'},
  {'profile': 'assets/profile/profile1.jpg', 'name': 'Terry'},
  {'profile': 'assets/profile/profile8.jpg', 'name': 'Terry'},
  {'profile': 'assets/profile/profile9.jpg', 'name': 'Craig'},
  {'profile': 'assets/profile/profile6.jpg', 'name': 'Roger'},
  {'profile': 'assets/profile/profile4.jpg', 'name': 'noian'},
  {'profile': 'assets/profile/profile1.jpg', 'name': 'Terry'},
  {'profile': 'assets/profile/profile8.jpg', 'name': 'Terry'},
  {'profile': 'assets/profile/profile9.jpg', 'name': 'Craig'},
  {'profile': 'assets/profile/profile6.jpg', 'name': 'Roger'},
  {'profile': 'assets/profile/profile4.jpg', 'name': 'noian'},
  {'profile': 'assets/profile/profile1.jpg', 'name': 'Terry'},
];

List<String> emojisdata = [
  'assets/emoji/emoji1.png',
  'assets/emoji/emoji2.png',
  'assets/emoji/emoji3.png',
  'assets/emoji/emoji4.png',
  'assets/emoji/emoji5.png',
  'assets/emoji/emoji7.png',
  'assets/emoji/emoji8.png',
  'assets/emoji/emoji9.png',
  'assets/emoji/emoji10.png',
];

List received_messages = [
  'Hi, Asal',
  'How do you buy "nice" Stuff?',
  "Plese help me find a good monitor for the design"
];

List send_messages = [
  'Hi,Asal',
  "I usually buy directly to the shop to reduce the risk of damaged travel, and prevent any damage"
];
