// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcxDVGUDZAUlOKBC5YMwRrXK35VvgWr4',
    appId: '1:528600756297:web:bcf331aabd2c216abfcf98',
    messagingSenderId: '528600756297',
    projectId: 'chat-app-92800',
    authDomain: 'chat-app-92800.firebaseapp.com',
    storageBucket: 'chat-app-92800.appspot.com',
    measurementId: 'G-EJPQCK6GFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxCTmWd9K_UV8mH9XLcDNsiJCZhSEeNTU',
    appId: '1:528600756297:android:fbec40e85afb3badbfcf98',
    messagingSenderId: '528600756297',
    projectId: 'chat-app-92800',
    storageBucket: 'chat-app-92800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9yCjTi77isyZFE-xE0w93hwPR-QDpzM',
    appId: '1:528600756297:ios:bba0237ca6d725d1bfcf98',
    messagingSenderId: '528600756297',
    projectId: 'chat-app-92800',
    storageBucket: 'chat-app-92800.appspot.com',
    iosBundleId: 'com.example.mangochatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9yCjTi77isyZFE-xE0w93hwPR-QDpzM',
    appId: '1:528600756297:ios:24a49c477a9931e7bfcf98',
    messagingSenderId: '528600756297',
    projectId: 'chat-app-92800',
    storageBucket: 'chat-app-92800.appspot.com',
    iosBundleId: 'com.example.mangochatapp.RunnerTests',
  );
}
